"""PostgreSQL-backed unified chat session store.

A drop-in alternative to ``SQLiteSessionStore`` / ``PocketBaseSessionStore`` that
satisfies :class:`SessionStoreProtocol`. It exists to make DeepTutor's App layer
**stateless and horizontally scalable**: with sessions/turns/messages/events in a
shared Postgres, any replica can read/write any session, and replica restart no
longer loses state.

Why this is faster than the SQLite store under concurrency
----------------------------------------------------------
``SQLiteSessionStore`` serializes *every* DB operation through a single
``asyncio.Lock`` + ``asyncio.to_thread`` (sqlite_store.py:80,376) — a per-process
global mutex. This store uses an asyncpg connection pool, so independent sessions'
operations run concurrently. Turn-event ``seq`` assignment stays correct via a
*per-turn* transactional advisory lock (narrower than a global lock).

Selection (see services/session/__init__.get_session_store):
    DEEPTUTOR_PG_DSN set  -> PostgresSessionStore
    pocketbase enabled    -> PocketBaseSessionStore
    else                  -> SQLiteSessionStore (local default)

Scope: single shared database (matches the single-user engine deployment, where
ENABLE_AUTH=false and MathVerse owns multi-tenancy at the BFF layer). Per-user
row scoping for engine-level multi-user auth is a follow-up.

Delivered as a build-time overlay file (see deeptutor-patch). Return shapes mirror
SQLiteSessionStore exactly so callers (turn_runtime, routers) need no changes.
"""

from __future__ import annotations

import asyncio
import json
import os
import time
from typing import Any
import uuid

import asyncpg


def _json_dumps(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False)


def _json_loads(value: str | None, default: Any) -> Any:
    if not value:
        return default
    try:
        return json.loads(value)
    except (json.JSONDecodeError, TypeError):
        return default


# Sentinel mirroring sqlite_store: distinguishes "auto-pick latest as parent"
# from "explicitly attach at the session root (parent = NULL)".
class _Unset:
    pass


_PARENT_AUTO = _Unset()


_SCHEMA = """
CREATE TABLE IF NOT EXISTS sessions (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL DEFAULT 'New conversation',
    created_at DOUBLE PRECISION NOT NULL,
    updated_at DOUBLE PRECISION NOT NULL,
    compressed_summary TEXT DEFAULT '',
    summary_up_to_msg_id BIGINT DEFAULT 0,
    preferences_json TEXT DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    role TEXT NOT NULL,
    content TEXT NOT NULL DEFAULT '',
    capability TEXT DEFAULT '',
    events_json TEXT DEFAULT '',
    attachments_json TEXT DEFAULT '',
    metadata_json TEXT DEFAULT '{}',
    created_at DOUBLE PRECISION NOT NULL,
    parent_message_id BIGINT
);

CREATE INDEX IF NOT EXISTS idx_messages_session_created
    ON messages(session_id, created_at, id);
CREATE INDEX IF NOT EXISTS idx_messages_parent
    ON messages(session_id, parent_message_id);
CREATE INDEX IF NOT EXISTS idx_sessions_updated_at
    ON sessions(updated_at DESC);

CREATE TABLE IF NOT EXISTS turns (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    capability TEXT DEFAULT '',
    status TEXT NOT NULL DEFAULT 'running',
    error TEXT DEFAULT '',
    created_at DOUBLE PRECISION NOT NULL,
    updated_at DOUBLE PRECISION NOT NULL,
    finished_at DOUBLE PRECISION
);

CREATE INDEX IF NOT EXISTS idx_turns_session_updated
    ON turns(session_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_turns_session_status
    ON turns(session_id, status, updated_at DESC);

CREATE TABLE IF NOT EXISTS turn_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    turn_id TEXT NOT NULL REFERENCES turns(id) ON DELETE CASCADE,
    seq BIGINT NOT NULL,
    type TEXT NOT NULL,
    source TEXT DEFAULT '',
    stage TEXT DEFAULT '',
    content TEXT DEFAULT '',
    metadata_json TEXT DEFAULT '',
    timestamp DOUBLE PRECISION NOT NULL,
    created_at DOUBLE PRECISION NOT NULL,
    UNIQUE(turn_id, seq)
);

CREATE INDEX IF NOT EXISTS idx_turn_events_turn_seq
    ON turn_events(turn_id, seq);
"""


def _rowcount(tag: str) -> int:
    """asyncpg execute() returns a command tag like 'UPDATE 1' / 'DELETE 0'."""
    try:
        return int(tag.split()[-1])
    except (ValueError, IndexError):
        return 0


class PostgresSessionStore:
    """Persist unified chat sessions, turns, messages and the seq'd event log."""

    def __init__(self, dsn: str | None = None, *, min_size: int = 1, max_size: int = 20,
                 command_timeout: float = 30.0) -> None:
        self._dsn = dsn or os.environ.get("DEEPTUTOR_PG_DSN")
        if not self._dsn:
            raise RuntimeError("PostgresSessionStore requires DEEPTUTOR_PG_DSN")
        self._min_size = min_size
        self._max_size = max_size
        # Bound every statement so a stuck query can't hang a worker indefinitely
        # (the face-B sync bridge blocks the main loop on these calls).
        self._command_timeout = command_timeout
        self._pool: asyncpg.Pool | None = None
        self._init_lock = asyncio.Lock()

    async def _get_pool(self) -> asyncpg.Pool:
        """Lazily create the pool and ensure the schema, once per process.

        The lock guards *initialization only* (not every op), so it does not
        reintroduce the SQLite store's per-op global serialization.
        """
        if self._pool is not None:
            return self._pool
        async with self._init_lock:
            if self._pool is None:
                pool = await asyncpg.create_pool(
                    self._dsn, min_size=self._min_size, max_size=self._max_size,
                    command_timeout=self._command_timeout,
                )
                async with pool.acquire() as conn:
                    await conn.execute(_SCHEMA)
                self._pool = pool
        return self._pool

    # ── Sessions ──────────────────────────────────────────────────────

    async def create_session(
        self,
        title: str | None = None,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        pool = await self._get_pool()
        now = time.time()
        resolved_id = session_id or f"unified_{int(now * 1000)}_{uuid.uuid4().hex[:8]}"
        resolved_title = ((title or "New conversation").strip() or "New conversation")[:100]
        async with pool.acquire() as conn:
            await conn.execute(
                """
                INSERT INTO sessions (
                    id, title, created_at, updated_at, compressed_summary, summary_up_to_msg_id
                ) VALUES ($1, $2, $3, $3, '', 0)
                """,
                resolved_id, resolved_title, now,
            )
        return {
            "id": resolved_id,
            "session_id": resolved_id,
            "title": resolved_title,
            "created_at": now,
            "updated_at": now,
            "compressed_summary": "",
            "summary_up_to_msg_id": 0,
        }

    async def get_session(self, session_id: str) -> dict[str, Any] | None:
        pool = await self._get_pool()
        async with pool.acquire() as conn:
            row = await conn.fetchrow(
                """
                SELECT
                    s.id, s.title, s.created_at, s.updated_at,
                    s.compressed_summary, s.summary_up_to_msg_id, s.preferences_json,
                    COALESCE((SELECT t.status FROM turns t WHERE t.session_id = s.id
                              ORDER BY t.updated_at DESC LIMIT 1), 'idle') AS status,
                    COALESCE((SELECT t.id FROM turns t WHERE t.session_id = s.id
                              AND t.status = 'running' ORDER BY t.updated_at DESC LIMIT 1), '')
                        AS active_turn_id,
                    COALESCE((SELECT t.capability FROM turns t WHERE t.session_id = s.id
                              ORDER BY t.updated_at DESC LIMIT 1), '') AS capability
                FROM sessions s
                WHERE s.id = $1
                """,
                session_id,
            )
        if row is None:
            return None
        payload = dict(row)
        payload["session_id"] = payload["id"]
        payload["preferences"] = _json_loads(payload.pop("preferences_json", ""), {})
        return payload

    async def ensure_session(self, session_id: str | None = None) -> dict[str, Any]:
        if session_id:
            session = await self.get_session(session_id)
            if session is not None:
                return session
        return await self.create_session()

    async def update_session_title(self, session_id: str, title: str) -> bool:
        pool = await self._get_pool()
        async with pool.acquire() as conn:
            tag = await conn.execute(
                "UPDATE sessions SET title = $1, updated_at = $2 WHERE id = $3",
                (title.strip() or "New conversation")[:100], time.time(), session_id,
            )
        return _rowcount(tag) > 0

    async def delete_session(self, session_id: str) -> bool:
        pool = await self._get_pool()
        async with pool.acquire() as conn:
            tag = await conn.execute("DELETE FROM sessions WHERE id = $1", session_id)
        return _rowcount(tag) > 0

    async def list_sessions(self, limit: int = 50, offset: int = 0) -> list[dict[str, Any]]:
        pool = await self._get_pool()
        async with pool.acquire() as conn:
            rows = await conn.fetch(
                """
                SELECT
                    s.id, s.title, s.created_at, s.updated_at,
                    s.compressed_summary, s.summary_up_to_msg_id, s.preferences_json,
                    COUNT(m.id) AS message_count,
                    COALESCE((SELECT t.status FROM turns t WHERE t.session_id = s.id
                              ORDER BY t.updated_at DESC LIMIT 1), 'idle') AS status,
                    COALESCE((SELECT t.id FROM turns t WHERE t.session_id = s.id
                              AND t.status = 'running' ORDER BY t.updated_at DESC LIMIT 1), '')
                        AS active_turn_id,
                    COALESCE((SELECT t.capability FROM turns t WHERE t.session_id = s.id
                              ORDER BY t.updated_at DESC LIMIT 1), '') AS capability,
                    COALESCE((SELECT m2.content FROM messages m2 WHERE m2.session_id = s.id
                              AND TRIM(COALESCE(m2.content, '')) != ''
                              ORDER BY m2.id DESC LIMIT 1), '') AS last_message
                FROM sessions s
                LEFT JOIN messages m ON m.session_id = s.id
                GROUP BY s.id
                ORDER BY s.updated_at DESC
                LIMIT $1 OFFSET $2
                """,
                limit, offset,
            )
        sessions = []
        for row in rows:
            payload = dict(row)
            payload["session_id"] = payload["id"]
            payload["message_count"] = int(payload.get("message_count") or 0)
            payload["preferences"] = _json_loads(payload.pop("preferences_json", ""), {})
            sessions.append(payload)
        return sessions

    async def update_summary(self, session_id: str, summary: str, up_to_msg_id: int) -> bool:
        pool = await self._get_pool()
        async with pool.acquire() as conn:
            tag = await conn.execute(
                "UPDATE sessions SET compressed_summary = $1, summary_up_to_msg_id = $2 WHERE id = $3",
                summary, max(0, int(up_to_msg_id)), session_id,
            )
        return _rowcount(tag) > 0

    async def update_session_preferences(
        self, session_id: str, preferences: dict[str, Any]
    ) -> bool:
        pool = await self._get_pool()
        async with pool.acquire() as conn:
            async with conn.transaction():
                current = await conn.fetchval(
                    "SELECT preferences_json FROM sessions WHERE id = $1 FOR UPDATE",
                    session_id,
                )
                if current is None:
                    return False
                merged = {**_json_loads(current, {}), **(preferences or {})}
                tag = await conn.execute(
                    "UPDATE sessions SET preferences_json = $1, updated_at = $2 WHERE id = $3",
                    _json_dumps(merged), time.time(), session_id,
                )
        return _rowcount(tag) > 0

    async def get_session_with_messages(self, session_id: str) -> dict[str, Any] | None:
        session = await self.get_session(session_id)
        if session is None:
            return None
        session["messages"] = await self.get_messages(session_id)
        session["active_turns"] = await self.list_active_turns(session_id)
        return session

    # ── Messages ──────────────────────────────────────────────────────

    @staticmethod
    def _serialize_message(row: asyncpg.Record) -> dict[str, Any]:
        keys = row.keys()
        parent_id = row["parent_message_id"] if "parent_message_id" in keys else None
        return {
            "id": int(row["id"]),
            "session_id": row["session_id"],
            "role": row["role"],
            "content": row["content"],
            "capability": row["capability"] or "",
            "events": _json_loads(row["events_json"], []),
            "attachments": _json_loads(row["attachments_json"], []),
            "metadata": _json_loads(row["metadata_json"], {}),
            "created_at": row["created_at"],
            "parent_message_id": int(parent_id) if parent_id is not None else None,
        }

    async def add_message(
        self,
        session_id: str,
        role: str,
        content: str,
        capability: str = "",
        events: list[dict[str, Any]] | None = None,
        attachments: list[dict[str, Any]] | None = None,
        metadata: dict[str, Any] | None = None,
        parent_message_id: int | None | _Unset = _PARENT_AUTO,
    ) -> int:
        pool = await self._get_pool()
        now = time.time()
        async with pool.acquire() as conn:
            async with conn.transaction():
                exists = await conn.fetchval("SELECT 1 FROM sessions WHERE id = $1", session_id)
                if exists is None:
                    raise ValueError(f"Session not found: {session_id}")

                if isinstance(parent_message_id, _Unset):
                    last_id = await conn.fetchval(
                        "SELECT id FROM messages WHERE session_id = $1 ORDER BY id DESC LIMIT 1",
                        session_id,
                    )
                    resolved_parent_id = int(last_id) if last_id is not None else None
                else:
                    resolved_parent_id = (
                        int(parent_message_id) if parent_message_id is not None else None
                    )

                new_id = await conn.fetchval(
                    """
                    INSERT INTO messages (
                        session_id, role, content, capability, events_json,
                        attachments_json, metadata_json, created_at, parent_message_id
                    ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
                    RETURNING id
                    """,
                    session_id, role, content or "", capability or "",
                    _json_dumps(events or []), _json_dumps(attachments or []),
                    _json_dumps(metadata or {}), now, resolved_parent_id,
                )
                await conn.execute(
                    "UPDATE sessions SET updated_at = $1 WHERE id = $2", now, session_id
                )
        return int(new_id)

    async def delete_message(self, message_id: int | str) -> bool:
        pool = await self._get_pool()
        async with pool.acquire() as conn:
            tag = await conn.execute("DELETE FROM messages WHERE id = $1", int(message_id))
        return _rowcount(tag) > 0

    async def get_last_message(
        self, session_id: str, role: str | None = None
    ) -> dict[str, Any] | None:
        pool = await self._get_pool()
        cols = (
            "id, session_id, role, content, capability, events_json, "
            "attachments_json, metadata_json, created_at, parent_message_id"
        )
        async with pool.acquire() as conn:
            if role is None:
                row = await conn.fetchrow(
                    f"SELECT {cols} FROM messages WHERE session_id = $1 ORDER BY id DESC LIMIT 1",
                    session_id,
                )
            else:
                row = await conn.fetchrow(
                    f"SELECT {cols} FROM messages WHERE session_id = $1 AND role = $2 "
                    "ORDER BY id DESC LIMIT 1",
                    session_id, role,
                )
        return self._serialize_message(row) if row is not None else None

    async def get_messages(self, session_id: str) -> list[dict[str, Any]]:
        pool = await self._get_pool()
        async with pool.acquire() as conn:
            rows = await conn.fetch(
                """
                SELECT id, session_id, role, content, capability, events_json,
                       attachments_json, metadata_json, created_at, parent_message_id
                FROM messages WHERE session_id = $1 ORDER BY id ASC
                """,
                session_id,
            )
        return [self._serialize_message(row) for row in rows]

    async def get_messages_for_context(
        self, session_id: str, leaf_message_id: int | None = None
    ) -> list[dict[str, Any]]:
        pool = await self._get_pool()
        async with pool.acquire() as conn:
            if leaf_message_id is None:
                rows = await conn.fetch(
                    """
                    SELECT id, role, content FROM messages
                    WHERE session_id = $1 AND role IN ('user', 'assistant', 'system')
                    ORDER BY id ASC
                    """,
                    session_id,
                )
                return [
                    {"id": int(r["id"]), "role": r["role"], "content": r["content"] or ""}
                    for r in rows
                ]
            # Branch-aware path walk: include only ancestors (+ leaf) so sibling
            # branches at any depth are excluded from LLM context.
            chain: list[dict[str, Any]] = []
            current: int | None = int(leaf_message_id)
            safety = 10_000
            while current is not None and safety > 0:
                row = await conn.fetchrow(
                    """
                    SELECT id, role, content, parent_message_id FROM messages
                    WHERE id = $1 AND session_id = $2
                      AND role IN ('user', 'assistant', 'system')
                    """,
                    current, session_id,
                )
                if row is None:
                    break
                chain.append({"id": int(row["id"]), "role": row["role"], "content": row["content"] or ""})
                parent = row["parent_message_id"]
                current = int(parent) if parent is not None else None
                safety -= 1
        chain.reverse()
        return chain

    # ── Turns ─────────────────────────────────────────────────────────

    @staticmethod
    def _serialize_turn(row: asyncpg.Record) -> dict[str, Any]:
        keys = row.keys()
        return {
            "id": row["id"],
            "turn_id": row["id"],
            "session_id": row["session_id"],
            "capability": row["capability"] or "",
            "status": row["status"] or "running",
            "error": row["error"] or "",
            "created_at": row["created_at"],
            "updated_at": row["updated_at"],
            "finished_at": row["finished_at"],
            "last_seq": int(row["last_seq"]) if "last_seq" in keys and row["last_seq"] is not None else 0,
        }

    async def create_turn(self, session_id: str, capability: str = "") -> dict[str, Any]:
        pool = await self._get_pool()
        now = time.time()
        turn_id = f"turn_{int(now * 1000)}_{uuid.uuid4().hex[:10]}"
        async with pool.acquire() as conn:
            async with conn.transaction():
                exists = await conn.fetchval("SELECT 1 FROM sessions WHERE id = $1", session_id)
                if exists is None:
                    raise ValueError(f"Session not found: {session_id}")
                active = await conn.fetchval(
                    "SELECT id FROM turns WHERE session_id = $1 AND status = 'running' "
                    "ORDER BY updated_at DESC LIMIT 1",
                    session_id,
                )
                if active is not None:
                    raise RuntimeError(f"Session already has an active turn: {active}")
                await conn.execute(
                    """
                    INSERT INTO turns (id, session_id, capability, status, error,
                                       created_at, updated_at, finished_at)
                    VALUES ($1, $2, $3, 'running', '', $4, $4, NULL)
                    """,
                    turn_id, session_id, capability or "", now,
                )
        return {
            "id": turn_id, "turn_id": turn_id, "session_id": session_id,
            "capability": capability or "", "status": "running", "error": "",
            "created_at": now, "updated_at": now, "finished_at": None, "last_seq": 0,
        }

    async def get_turn(self, turn_id: str) -> dict[str, Any] | None:
        pool = await self._get_pool()
        async with pool.acquire() as conn:
            row = await conn.fetchrow(
                """
                SELECT t.*,
                    COALESCE((SELECT MAX(seq) FROM turn_events te WHERE te.turn_id = t.id), 0)
                        AS last_seq
                FROM turns t WHERE t.id = $1
                """,
                turn_id,
            )
        return self._serialize_turn(row) if row is not None else None

    async def get_active_turn(self, session_id: str) -> dict[str, Any] | None:
        pool = await self._get_pool()
        async with pool.acquire() as conn:
            row = await conn.fetchrow(
                """
                SELECT t.*,
                    COALESCE((SELECT MAX(seq) FROM turn_events te WHERE te.turn_id = t.id), 0)
                        AS last_seq
                FROM turns t WHERE t.session_id = $1 AND t.status = 'running'
                ORDER BY t.updated_at DESC LIMIT 1
                """,
                session_id,
            )
        return self._serialize_turn(row) if row is not None else None

    async def list_active_turns(self, session_id: str) -> list[dict[str, Any]]:
        pool = await self._get_pool()
        async with pool.acquire() as conn:
            rows = await conn.fetch(
                """
                SELECT t.*,
                    COALESCE((SELECT MAX(seq) FROM turn_events te WHERE te.turn_id = t.id), 0)
                        AS last_seq
                FROM turns t WHERE t.session_id = $1 AND t.status = 'running'
                ORDER BY t.updated_at DESC
                """,
                session_id,
            )
        return [self._serialize_turn(row) for row in rows]

    async def update_turn_status(self, turn_id: str, status: str, error: str = "") -> bool:
        pool = await self._get_pool()
        now = time.time()
        finished_at = now if status in {"completed", "failed", "cancelled"} else None
        async with pool.acquire() as conn:
            tag = await conn.execute(
                "UPDATE turns SET status = $1, error = $2, updated_at = $3, finished_at = $4 "
                "WHERE id = $5",
                status, error or "", now, finished_at, turn_id,
            )
        return _rowcount(tag) > 0

    async def touch_turn(self, turn_id: str) -> bool:
        """Owner liveness heartbeat: bump updated_at while the turn is still running.

        Lets a foreign tailer's staleness check reflect REAL owner liveness rather
        than mere event activity — without this, a turn that runs a long quiet step
        (no streamed events for > the tailer's stale window) gets wrongly failed by a
        non-owning replica. Only the running owner calls this (turn_runtime _run_turn).
        """
        pool = await self._get_pool()
        async with pool.acquire() as conn:
            tag = await conn.execute(
                "UPDATE turns SET updated_at = $1 WHERE id = $2 AND status = 'running'",
                time.time(), turn_id,
            )
        return _rowcount(tag) > 0

    async def append_turn_event(self, turn_id: str, event: dict[str, Any]) -> dict[str, Any]:
        pool = await self._get_pool()
        now = time.time()
        async with pool.acquire() as conn:
            async with conn.transaction():
                # Per-turn advisory lock makes seq assignment correct under
                # concurrent appends WITHOUT a global mutex (narrower than the
                # SQLite store's single asyncio.Lock).
                await conn.execute("SELECT pg_advisory_xact_lock(hashtext($1), 0)", turn_id)
                session_id = await conn.fetchval(
                    "SELECT session_id FROM turns WHERE id = $1", turn_id
                )
                if session_id is None:
                    raise ValueError(f"Turn not found: {turn_id}")
                provided_seq = int(event.get("seq") or 0)
                if provided_seq > 0:
                    seq = provided_seq
                else:
                    last_seq = await conn.fetchval(
                        "SELECT COALESCE(MAX(seq), 0) FROM turn_events WHERE turn_id = $1", turn_id
                    )
                    seq = int(last_seq or 0) + 1
                payload = dict(event)
                payload["seq"] = seq
                payload["turn_id"] = payload.get("turn_id") or turn_id
                payload["session_id"] = payload.get("session_id") or session_id
                await conn.execute(
                    """
                    INSERT INTO turn_events (
                        turn_id, seq, type, source, stage, content, metadata_json,
                        timestamp, created_at
                    ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
                    ON CONFLICT (turn_id, seq) DO UPDATE SET
                        type = EXCLUDED.type, source = EXCLUDED.source,
                        stage = EXCLUDED.stage, content = EXCLUDED.content,
                        metadata_json = EXCLUDED.metadata_json,
                        timestamp = EXCLUDED.timestamp
                    """,
                    turn_id, seq, payload.get("type", ""), payload.get("source", ""),
                    payload.get("stage", ""), payload.get("content", "") or "",
                    _json_dumps(payload.get("metadata", {})),
                    float(payload.get("timestamp") or now), now,
                )
                await conn.execute("UPDATE turns SET updated_at = $1 WHERE id = $2", now, turn_id)
        return payload

    async def get_turn_events(self, turn_id: str, after_seq: int = 0) -> list[dict[str, Any]]:
        pool = await self._get_pool()
        async with pool.acquire() as conn:
            rows = await conn.fetch(
                """
                SELECT turn_id, seq, type, source, stage, content, metadata_json, timestamp
                FROM turn_events WHERE turn_id = $1 AND seq > $2 ORDER BY seq ASC
                """,
                turn_id, max(0, int(after_seq)),
            )
            session_id = await conn.fetchval(
                "SELECT session_id FROM turns WHERE id = $1", turn_id
            )
        session_id = session_id or ""
        return [
            {
                "type": row["type"],
                "source": row["source"] or "",
                "stage": row["stage"] or "",
                "content": row["content"] or "",
                "metadata": _json_loads(row["metadata_json"], {}),
                "session_id": session_id,
                "turn_id": row["turn_id"],
                "seq": int(row["seq"]),
                "timestamp": row["timestamp"],
            }
            for row in rows
        ]


_instance: PostgresSessionStore | None = None


def get_postgres_session_store() -> PostgresSessionStore:
    """Process-wide singleton (pool is created lazily on first use)."""
    global _instance
    if _instance is None:
        _instance = PostgresSessionStore()
    return _instance


__all__ = ["PostgresSessionStore", "get_postgres_session_store"]
