export default defineAppConfig({
  pages: [
    'pages/index/index',
    'pages/solve/index',
    'pages/learn/index',
    'pages/me/index',
    'pages/mistakes/index',
    'pages/plan/index',
    'pages/score/index',
    'pages/membership/index',
    'pages/login/index',
    'pages/settings/index',
    'pages/kb/index',
    'pages/tutor/index',
    'pages/visualize/index',
    'pages/notebook/index',
    'pages/activity/index',
    'pages/memory/index',
    'pages/book/index',
  ],
  tabBar: {
    color: '#8b8fa6',
    selectedColor: '#4F46E5',
    backgroundColor: '#ffffff',
    list: [
      { pagePath: 'pages/index/index', text: '首页', iconPath: 'assets/tab/home.png', selectedIconPath: 'assets/tab/home-on.png' },
      { pagePath: 'pages/solve/index', text: '解题', iconPath: 'assets/tab/solve.png', selectedIconPath: 'assets/tab/solve-on.png' },
      { pagePath: 'pages/learn/index', text: '学习', iconPath: 'assets/tab/learn.png', selectedIconPath: 'assets/tab/learn-on.png' },
      { pagePath: 'pages/me/index', text: '我的', iconPath: 'assets/tab/me.png', selectedIconPath: 'assets/tab/me-on.png' },
    ],
  },
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#4F46E5',
    navigationBarTitleText: '数界 MathVerse',
    navigationBarTextStyle: 'white',
  },
});
